force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Tracks grocery products and their details.</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Stock_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Stock_Quantity__c</fullName>
    <label>Stock Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/findProductClass.cls
public with sharing class findProductClass {
    @AuraEnabled(cacheable = true)
    public static List<Product__c> getProduct(String searchText){
        try {
            searchText = '%' + searchText + '%';
            return [SELECT Name, Category__c, IsActive__c, Unit__c, Stock_Quantity__c, Unit_Price__c 
                    FROM Product__c 
                    WHERE Name LIKE :searchText 
                    LIMIT 5];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }   
}